### PR TITLE
Upgrade Spark dependency from 3.0.0 to 3.1.2

### PR DESCRIPTION
**Pull request by karenfeng**
## What changes are proposed in this pull request?

Works on issue #387 by upgrading Glow's Spark 3 build to use Spark 3.1.2.

This enables interoperability with Hail, whose Spark 3.x versions are built for Spark 3.1.

Follow up steps:

- Release Glow 1.1.0 with Spark 3.1.2 dependency
- Modify notebook tests to use Glow 1.1.0
- Merge in Hail notebooks

## How is this patch tested?
- [x] Unit tests
- [x] Integration tests
- [ ] Manual tests

### CODE REVIEW

File: python/glow/functions.py [hunk 1]
```diff
@@ -490,10 +490,10 @@ def sample_call_summary_stats(genotypes: Union[Column, str], refAllele: Union[Co
 
     Examples:
         >>> sites = [
-        ... Row(refAllele='C', alternateAlleles=['G'], genotypes=[Row(sampleId='NA12878', calls=[0, 0])]),
-        ... Row(refAllele='A', alternateAlleles=['G'], genotypes=[Row(sampleId='NA12878', calls=[1, 1])]),
-        ... Row(refAllele='AG', alternateAlleles=['A'], genotypes=[Row(sampleId='NA12878', calls=[1, 0])])]
-        >>> df = spark.createDataFrame(sites, 'alternateAlleles: array<string>, genotypes: array<struct<sampleId: string, calls: array<int>>>, refAllele: string')
+        ... {'refAllele': 'C', 'alternateAlleles': ['G'], 'genotypes': [{'sampleId': 'NA12878', 'calls': [0, 0]}]},
```
Comment (karenfeng) [inline python/glow/functions.py:493]: PySpark stopped sorting Row fields in Spark 3.x, so this broke the tests. See https://spark.apache.org/docs/3.0.1/pyspark-migration-guide.html: we would have to set the environment variable PYSPARK_ROW_FIELD_SORTING_ENABLED to true for both executors and driver.

File: core/src/test/scala/io/projectglow/tertiary/AggregateByIndexSuite.scala [hunk 2]
```diff
@@ -150,7 +150,7 @@ class AggregateByIndexSuite extends GlowBaseTest {
         """.stripMargin)
       .as[Seq[Int]]
       .head
-    // null if Spark 3.0, empty list if Spark 2.4
+    // null if Spark 3.x, empty list if Spark 2.4
```
Comment (kianfar77) [inline core/src/test/scala/io/projectglow/tertiary/AggregateByIndexSuite.scala:153]: Can we depend these directly on spark.version instead of OR?

File: python/glow/functions.py (hunk 1 above)
Comment (kianfar77) [reply python/glow/functions.py:493]: We need to document this for developers.

**Review by kianfar77 — APPROVED** [review]
Thanks @karenfeng for this. Left a couple of comments. Otherwise great.

File: python/glow/functions.py (hunk 1 above)
Comment (karenfeng) [reply python/glow/functions.py:493]: We should point to the migration guides in the release notes, but I'm not sure where else to document this. What do you think?

Comment (williambrandler) [reply python/glow/functions.py:493]: notebooks are not working with the new version of spark 3.1.2
Did you test the notebooks with this version of Spark?

When reading a VCF with Glow v1.1.0 and
`PYSPARK_ROW_FIELD_SORTING_ENABLED=true`

I get:

`java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformAllExpressions(Lscala/PartialFunction;)Lorg/apache/spark/sql/catalyst/plans/logical/LogicalPlan;`

Any idea how to resolve this?

Comment (williambrandler) [reply python/glow/functions.py:493]: Also the notebook tests only test changed notebooks, but for a new version would want to change all of them?

Comment (williambrandler) [reply python/glow/functions.py:493]: this was caused by a regression in Spark, which will be resolved soon
https://databricks.atlassian.net/browse/SC-84055
will continue with the release once this is in
